version: "3"
services:
  service-1:
    image: lb-example:1.0
  service-2:
    image: lb-example:1.0
  load-balancer:
    image: nginx:1.15.10
    depends_on:
      - service-1
      - service-2
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
